#### Auto Mpg

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
import seaborn as sns
from sklearn import preprocessing

In [ ]:
df = pd.read_csv('auto-mpg.csv')
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [3]:
df.head()
df.shape
df.columns
df.dtypes
df.duplicated().sum()
df.nunique()
df.cylinders.nunique()
df.info()
df.describe()
df.isnull().sum()
df.corr(numeric_only = True)
df['cylinders'].value_counts()
df['origin'].value_counts().to_frame()
(df['horsepower'].str.isnumeric() == False).sum()
(df['horsepower'] == '?').sum()
df[df['horsepower'] == '?']

df[df['origin'] == 1].shape
df[df['origin'] == 2].shape
df[df['origin'] == 3].shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

(79, 9)

#### Data Cleaning

In [4]:
df = df.drop('car name', axis = 1)
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,18.0,8,307.0,130,3504,12.0,70,1
1,15.0,8,350.0,165,3693,11.5,70,1
2,18.0,8,318.0,150,3436,11.0,70,1
3,16.0,8,304.0,150,3433,12.0,70,1
4,17.0,8,302.0,140,3449,10.5,70,1

In [5]:
df = df.replace('?', np.nan)

In [6]:
df = df.apply(lambda x: x.fillna(x.mode()[0]), axis = 0)
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,18.0,8,307.0,130,3504,12.0,70,1
1,15.0,8,350.0,165,3693,11.5,70,1
2,18.0,8,318.0,150,3436,11.0,70,1
3,16.0,8,304.0,150,3433,12.0,70,1
4,17.0,8,302.0,140,3449,10.5,70,1
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1
394,44.0,4,97.0,52,2130,24.6,82,2
395,32.0,4,135.0,84,2295,11.6,82,1
396,28.0,4,120.0,79,2625,18.6,82,1
397,31.0,4,119.0,82,2720,19.4,82,1

In [ ]:
df.info()

In [ ]:
df['horsepower'] = df['horsepower'].astype(int)
df.info()

#### Data Visualization

In [ ]:
plt.figure(figsize = (12, 8))
corr = df.corr()
mask = np.triu(corr)
sns.heatmap(corr, square = True, annot = True, mask = mask, fmt = '.2f')
plt.show()

In [ ]:
plt.figure(figsize = (10, 5))
ax = sns.countplot(data = df, x = 'origin')
ax.bar_label(ax.containers[0], label_type = 'edge')
plt.title('origin distribution')
plt.xlabel('origin')
plt.ylabel('cars count')
plt.show()

In [ ]:
plt.figure(figsize = (10, 5))
sns.pointplot(x = 'model year', y = 'mpg', hue = 'origin', data = df, errorbar = None)
plt.title('model year - mpg based on origin')
plt.xlabel('model year')
plt.ylabel('mpg')
plt.show()

In [ ]:
plt.figure(figsize = (10, 5))
plt.xlabel('year', fontsize = 15)
plt.ylabel('mpg', fontsize = 15)
sns.lineplot(x = 'model year', y = 'mpg', data = df)

In [ ]:
ax = sns.countplot(x = 'cylinders', data = df, color = '#4287f5')
ax.bar_label(ax.containers[0], label_type = 'edge')
plt.xlabel('cylinders', fontsize = 15)
plt.ylabel('cars count', fontsize = 15)
plt.show()

In [ ]:
sns.scatterplot(x = 'horsepower', y = 'mpg', data = df)
plt.title('horsepower - mpg')
plt.xlabel('horsepower')
plt.ylabel('mpg')
plt.show()

#### Create Model

In [ ]:
X = df.drop('mpg',  axis = 1)
y = df[['mpg']]
X.shape, y.shape

In [ ]:
# X_scaled = preprocessing.scale(X)
# X_scaled = pd.DataFrame(X_scaled, columns = X.columns)

# y_scaled = preprocessing.scale(y)
# y_scaled = pd.DataFrame(y_scaled, columns = y.columns)

# X_scaled.shape, y_scaled.shape

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2, random_state = 42)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
data = {'y_Actual' : y_test, 'y_pred' : y_pred}

data

# df = pd.DataFrame(data, columns = ['y_Actual', 'y_pred'])
# df

In [ ]:
for i, col_name in enumerate(X_train.columns):
    print(f'Regression model coefficient for {col_name} =>\t\t\t{model.coef_[0][i]}')
    
print(f'intercept => {model.intercept_[0]}')

In [ ]:
ridge = Ridge(alpha = .2)
ridge.fit(X_train, y_train)

In [ ]:
for i, col_name in enumerate(X_train.columns):
    print(f'Regression model coefficient for {col_name} =>\t\t\t{ridge.coef_[i]}')
ridge.coef_

In [ ]:
print(ridge.score(X_train, y_train))
print(ridge.score(X_test, y_test))

In [ ]:
lasso = Lasso(alpha = .2)
lasso.fit(X_train, y_train)

In [ ]:
for i, col_name in enumerate(X_train.columns):
    print(f'Regression model coefficient for {col_name} =>\t\t\t{lasso.coef_[i]}')
lasso.coef_

In [ ]:
print(lasso.score(X_train, y_train))
print(lasso.score(X_test, y_test))

In [ ]:
from sklearn.model_selection import  cross_val_score
from sklearn.linear_model import Ridge
import numpy as np
X = df.drop('mpg',  axis = 1)
y = df[['mpg']]

alphas = [round(num, 1) for num in np.arange(.1, 1, .1)]
for a in alphas:
    print(f'--------------------------\nalpha : {a}')
    lasso = Lasso(alpha = a)
    lasso.fit(X_train, y_train)
    print(lasso.score(X_train, y_train))
    print(lasso.score(X_test, y_test))